### ISSUE TITLE
Clearing the environment breaks finding `valgrind`

### ISSUE THREAD

**Issue by mohe2015** [Joining7943/iai-callgrind#20] opened 2023-09-22 20:34 UTC
Hi,

(I'm using the unreleased `main` branch)
on NixOS you can install packages in your current shell (on other distros you could probably just do `export PATH=...:$PATH`). Therefore the `valgrind` binary is not found because  `env_clear` seems to resets the `PATH` also for calling the `valgrind` binary.
`config = iai_callgrind::LibraryBenchmarkConfig::default().env_clear(true).pass_through_envs(["PATH"]);` works around the issue.
Do you think it would make sense to either unset that variable at a later stage or resolve the path to valgrind before so this would work?

**Comment by Joining7943** [comment] 2023-09-23 10:31
Hi!

> Therefore the valgrind binary is not found because env_clear seems to resets the PATH also for calling the valgrind binary.

Yeah, `env_clear` is only meant to clear the environment variables of the benchmarks, but not `valgrind` itself.

> Do you think it would make sense to either unset that variable at a later stage or resolve the path to valgrind before so this would work?

Resolving the path to valgrind before the environment is cleared would be the best solution in my opinion. I'll have a look into it asap.

**Comment by Joining7943** [comment] 2023-09-25 02:03
I couldn't reproduce this issue neither locally nor in the CI. I guess this is somehow related to `NixOS`. However, I changed the path resolution of valgrind and other needed binaries as described above.

Would you mind giving me some feedback if the fix is working for you? You can check out the https://github.com/Joining7943/iai-callgrind/tree/20-clearing-the-environment-breaks-finding-valgrind branch.

**Closed** 2023-09-27 10:44 UTC

**Comment by Joining7943** [comment] 2023-09-27 11:02
Hi! I published the version 0.7.1 including the fix for resolving the valgrind path etc. before clearing the environment variables. I hope it solves your problem but if not, don't hesitate to reopen this issue.
